In [1]:
import sys
import os
sys.path.append(os.path.abspath("../../src/vbpca_py"))

from rmempty import rmempty

In [2]:
import numpy as np
from scipy import sparse


# Example data
X_test = np.array([
    [1.0, 2.0, np.nan],
    [0.0, 0.0, 0.0],
    [3.0, 4.0, 5.0]
], dtype=float)

Xprobe_test = None
init_test = {'A': np.random.rand(3, 2), 'S': np.random.rand(3, 2)}
verbose_test = 2

# Call rmempty
X_clean, Xprobe_clean, Ir, Ic, init_clean = rmempty(X_test, Xprobe_test, init_test, verbose_test)

print("Cleaned X:\n", X_clean)
print("Cleaned Xprobe:", Xprobe_clean)
print("Ir:", Ir)
print("Ic:", Ic)
print("Updated init:", init_clean)


in rmempty
Checking for empty rows or columns...
No empty rows or columns
Cleaned X:
 [[ 1.  2. nan]
 [ 0.  0.  0.]
 [ 3.  4.  5.]]
Cleaned Xprobe: None
Ir: [0 1 2]
Ic: [0 1 2]
Updated init: {'A': array([[0.87008043, 0.16988905],
       [0.14565337, 0.82448269],
       [0.33841509, 0.63147599]]), 'S': array([[0.07711221, 0.19630065],
       [0.42699482, 0.28495922],
       [0.65497574, 0.46423352]])}


In [3]:
# Test Case 1: No empty rows or columns

import numpy as np

# Data matrices
X1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

Xprobe1 = np.array([[np.nan, 1, np.nan],
                    [np.nan, 2, np.nan],
                    [np.nan, 3, np.nan]])

# Initialize 'init1' dictionary
init1 = {
    "A": X1.copy(),
    "S": X1.copy(),
    "Av": [np.array([1, 1, 1])] * 3,
    "Sv": [np.eye(3)] * 3
}

verbose = 2
print('Test Case 1: No empty rows or columns')

# Call the rmempty function
X_res_p, Xprobe_res_p, Ir_p, Ic_p, init_res_p = rmempty(X1, Xprobe1, init1, verbose)

# Display the results
print('Python Results:')
print('X_res_p:')
print(X_res_p)
print('Ir_p:')
print(Ir_p)
print('Ic_p:')
print(Ic_p)
print('Xprobe_res_p:')
print(Xprobe_res_p)
print("init_res_p['A']:")
print(init_res_p['A'])
print("init_res_p['S']:")
print(init_res_p['S'])

Test Case 1: No empty rows or columns
in rmempty
Checking for empty rows or columns...
No empty rows or columns
Python Results:
X_res_p:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ir_p:
[0 1 2]
Ic_p:
[0 1 2]
Xprobe_res_p:
[[nan  1. nan]
 [nan  2. nan]
 [nan  3. nan]]
init_res_p['A']:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
init_res_p['S']:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Test Case 2: Some empty rows and columns

import numpy as np

# Data matrices
X2 = np.array([[1, np.nan, 3],
               [np.nan, np.nan, np.nan],
               [4, np.nan, 6]])

Xprobe2 = np.array([[np.nan, np.nan, np.nan],
                    [np.nan, 2, np.nan],
                    [7, np.nan, 8]])

# Initialize 'init2' dictionary
init2 = {
    "A": X2.copy(),
    "S": X2.copy(),
    "Av": [np.array([1, 1, 1])] * 3,
    "Sv": [np.eye(3)] * 3
}

verbose = 2
print('Test Case 2: Some empty rows and columns')

# Call the rmempty function
X_res_p, Xprobe_res_p, Ir_p, Ic_p, init_res_p = rmempty(X2, Xprobe2, init2, verbose)

# Display the results
print('Python Results:')
print('X_res_p:')
print(X_res_p)
print('Ir_p:')
print(Ir_p)
print('Ic_p:')
print(Ic_p)
print('Xprobe_res_p:')
print(Xprobe_res_p)
print("init_res_p['A']:")
print(init_res_p['A'])
print("init_res_p['S']:")
print(init_res_p['S'])


Test Case 2: Some empty rows and columns
in rmempty
Checking for empty rows or columns...
1 empty rows and 1 empty columns removed
Python Results:
X_res_p:
[[1. 3.]
 [4. 6.]]
Ir_p:
[0 2]
Ic_p:
[0 2]
Xprobe_res_p:
[[nan nan]
 [ 7.  8.]]
init_res_p['A']:
[[ 1. nan  3.]
 [ 4. nan  6.]]
init_res_p['S']:
[[ 1.  3.]
 [nan nan]
 [ 4.  6.]]


In [5]:
# Test Case 3: All values are NaNs

import numpy as np

# Data matrices
X3 = np.array([[np.nan, np.nan, np.nan],
               [np.nan, np.nan, np.nan],
               [np.nan, np.nan, np.nan]])

Xprobe3 = np.array([[np.nan, np.nan, np.nan],
                    [np.nan, np.nan, np.nan],
                    [np.nan, np.nan, np.nan]])

# Initialize 'init3' dictionary
init3 = {
    "A": X3.copy(),
    "S": X3.copy(),
    "Av": [np.array([1, 1, 1])] * 3,
    "Sv": [np.eye(3)] * 3
}

verbose = 2
print('Test Case 3: All values are NaNs')

# Call the rmempty function
X_res_p, Xprobe_res_p, Ir_p, Ic_p, init_res_p = rmempty(X3, Xprobe3, init3, verbose)

# Display the results
print('Python Results:')
print('X_res_p:')
print(X_res_p)
print('Ir_p:')
print(Ir_p)
print('Ic_p:')
print(Ic_p)
print('Xprobe_res_p:')
print(Xprobe_res_p)
print("init_res_p['A']:")
print(init_res_p['A'])
print("init_res_p['S']:")
print(init_res_p['S'])

Test Case 3: All values are NaNs
in rmempty
Checking for empty rows or columns...
3 empty rows and 3 empty columns removed
Python Results:
X_res_p:
[]
Ir_p:
[]
Ic_p:
[]
Xprobe_res_p:
[]
init_res_p['A']:
[]
init_res_p['S']:
[]


In [6]:
# Test Case 4: All values are zeros

import numpy as np

# Data matrices
X4 = np.array([[0, 0, 0],
               [0, 0, 0],
               [0, 0, 0]])

Xprobe4 = np.array([[0, 0, 0],
                    [0, 0, 0],
                    [0, 0, 0]])

# Initialize 'init4' dictionary
init4 = {
    "A": X4.copy(),
    "S": X4.copy(),
    "Av": [np.array([1, 1, 1])] * 3,
    "Sv": [np.eye(3)] * 3
}

verbose = 2
print('Test Case 4: All values are zeros')

# Call the rmempty function
X_res_p, Xprobe_res_p, Ir_p, Ic_p, init_res_p = rmempty(X4, Xprobe4, init4, verbose)

# Display the results
print('Python Results:')
print('X_res_p:')
print(X_res_p)
print('Ir_p:')
print(Ir_p)
print('Ic_p:')
print(Ic_p)
print('Xprobe_res_p:')
print(Xprobe_res_p)
print("init_res_p['A']:")
print(init_res_p['A'])
print("init_res_p['S']:")
print(init_res_p['S'])

Test Case 4: All values are zeros
in rmempty
Checking for empty rows or columns...
No empty rows or columns
Python Results:
X_res_p:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Ir_p:
[0 1 2]
Ic_p:
[0 1 2]
Xprobe_res_p:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
init_res_p['A']:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
init_res_p['S']:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
# Test Case 5: Matrix with empty columns, no probe data

import numpy as np

# Data matrix
X5 = np.array([[1, 0, 0],
               [4, 0, 0],
               [7, 0, 0]])

# Initialize 'init5' dictionary
init5 = {
    "A": X5.copy(),
    "S": X5.copy(),
    "Av": [np.array([1, 1, 1])] * 3,
    "Sv": [np.eye(3)] * 3
}

verbose = 2
print('Test Case 5: Empty columns, no Xprobe')

# No probe data
Xprobe5 = None

# Call the rmempty function
X_res_p, Xprobe_res_p, Ir_p, Ic_p, init_res_p = rmempty(X5, Xprobe5, init5, verbose)

# Display the results
print('Python Results:')
print('X_res_p:')
print(X_res_p)
print('Ir_p:')
print(Ir_p)
print('Ic_p:')
print(Ic_p)
print("init_res_p['A']:")
print(init_res_p['A'])
print("init_res_p['S']:")
print(init_res_p['S'])


Test Case 5: Empty columns, no Xprobe
in rmempty
Checking for empty rows or columns...
No empty rows or columns
Python Results:
X_res_p:
[[1 0 0]
 [4 0 0]
 [7 0 0]]
Ir_p:
[0 1 2]
Ic_p:
[0 1 2]
init_res_p['A']:
[[1 0 0]
 [4 0 0]
 [7 0 0]]
init_res_p['S']:
[[1 0 0]
 [4 0 0]
 [7 0 0]]


In [8]:
# Test Case 6: Sparse matrix with empty rows and columns

import numpy as np
from scipy import sparse

# Create sparse matrix X6
X6 = sparse.csr_matrix([
    [1, 0, 0],
    [0, 0, 0],
    [0, 0, 3]
])

# Initialize 'init6' dictionary with full matrices
init6 = {
    "A": X6.toarray(),
    "S": X6.toarray(),
    "Av": [np.array([1, 1, 1])] * 3,
    "Sv": [np.eye(3)] * 3
}

verbose = 2
print('Test Case 6: Sparse matrix with empty rows and columns')

Xprobe6 = None  # No probe data

# Call the rmempty function
X_res_p, Xprobe_res_p, Ir_p, Ic_p, init_res_p = rmempty(X6, Xprobe6, init6, verbose)

# Display the results
print('Python Results:')
print('X_res_p:')
print(X_res_p.toarray())
print('Ir_p:')
print(Ir_p)
print('Ic_p:')
print(Ic_p)
print("init_res_p['A']:")
print(init_res_p['A'])
print("init_res_p['S']:")
print(init_res_p['S'])

Test Case 6: Sparse matrix with empty rows and columns
in rmempty
Checking for empty rows or columns...
1 empty rows and 1 empty columns removed
Python Results:
X_res_p:
[[1 0]
 [0 3]]
Ir_p:
[0 2]
Ic_p:
[0 2]
init_res_p['A']:
[[1 0 0]
 [0 0 3]]
init_res_p['S']:
[[1 0]
 [0 0]
 [0 3]]
