In [3]:
from scipy.sparse import issparse

def Test(X, Xprobe):
    # Handle the case where X is sparse
    if issparse(X):
        M = (X != 0).astype(float)  # Equivalent to spones(X)
        Mprobe = (Xprobe != 0).astype(float)
    else:
        M = ~np.isnan(X)
        Mprobe = ~np.isnan(Xprobe)
    
        X[X == 0] = np.finfo(float).eps  # Replace zeros with a small number
        Xprobe[Xprobe == 0] = np.finfo(float).eps
    
        X[np.isnan(X)] = 0  # Replace NaNs with 0
        Xprobe[np.isnan(Xprobe)] = 0
    
    # Compute the number of observed (non-missing) values in each row of X
    Nobs_i = np.sum(M, axis=1)
    
    # Total number of observed data points
    ndata = np.sum(Nobs_i)
    
    # Compute the number of observed values in the probe data (Xprobe)
    if issparse(Mprobe):
        nprobe = Mprobe.count_nonzero()  # Use count_nonzero for sparse matrices
    else:
        nprobe = np.count_nonzero(Mprobe)
    # If no observed values in Xprobe, set it to empty and disable early stopping
    if nprobe == 0:
        Xprobe = np.array([])  # Set Xprobe to an empty array
        earlystop = 0  # Assuming we manually set the opts['earlystop'] to 0
    
    print("M (Observed values in X):\n", M, "\n")
    print("Nobs_i (Count of observed values in each row of X):ֿֿ\n", Nobs_i, "\n")
    print("ndata (Total number of observed data points):", ndata, "\n")
    print("Mprobe (Observed values in Xprobe):\n", Mprobe, "\n")
    print("nprobe (Number of observed values in Xprobe):", nprobe, "\n")
    print("Xprobe after processing:\n", Xprobe, "\n")

In [7]:
array = [1, 2, 3]
array2 = []

if (np.size(array) > 0):
    print("1")

if (np.size(array2) > 0):
    print("2")

if (np.size(array)):
    print("1")

if (np.size(array2)):
    print("2")

print (np.size(array))
print (np.size(array2))
print (np.size(array) > 0)
print (np.size(array) > 0)


1
1
3
0
True
True


In [4]:
import numpy as np

# Create test matrices with NaNs and zeros
X = np.array([[1, np.nan, 0], [0, 2, np.nan], [np.nan, 0, 3]])
Xprobe = np.array([[np.nan, 4, 0], [0, np.nan, 5], [6, 0, np.nan]])

# Run the test function
Test(X, Xprobe)


M (Observed values in X):
 [[ True False  True]
 [ True  True False]
 [False  True  True]] 

Nobs_i (Count of observed values in each row of X):ֿֿ
 [2 2 2] 

ndata (Total number of observed data points): 6 

Mprobe (Observed values in Xprobe):
 [[False  True  True]
 [ True False  True]
 [ True  True False]] 

nprobe (Number of observed values in Xprobe): 6 

Xprobe after processing:
 [[0.00000000e+00 4.00000000e+00 2.22044605e-16]
 [2.22044605e-16 0.00000000e+00 5.00000000e+00]
 [6.00000000e+00 2.22044605e-16 0.00000000e+00]] 



In [5]:
import numpy as np
from scipy.sparse import csr_matrix

# Create sparse test matrices
X = csr_matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
Xprobe = csr_matrix([[0, 4, 0], [0, 0, 5], [6, 0, 0]])

# Run the test function
Test(X, Xprobe)


M (Observed values in X):
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0 

Nobs_i (Count of observed values in each row of X):ֿֿ
 [[1.]
 [1.]
 [1.]] 

ndata (Total number of observed data points): 3.0 

Mprobe (Observed values in Xprobe):
   (0, 1)	1.0
  (1, 2)	1.0
  (2, 0)	1.0 

nprobe (Number of observed values in Xprobe): 3 

Xprobe after processing:
   (0, 1)	4
  (1, 2)	5
  (2, 0)	6 

