In [2]:
import numpy as np
from add_m_cols import add_m_cols
# Display function for Sv_new to match MATLAB structure
def display_sv_new(Sv_new):
    for idx, sv in enumerate(Sv_new, start=1):
        print(f"Column {idx}:")
        print(sv)

def run_tests():
    # Test Case 1: Basic Case with Observed and Unobserved Columns
    print("Python Test Case 1: Basic Case")
    S = np.array([[1, 2], [3, 4]])  # Observed data for 2 columns
    Sv = [np.eye(2), np.eye(2)]  # Covariance matrices for observed columns
    Ic = [1, 3]  # Observed columns at positions 1 and 3
    n2x = 4  # Total columns including unobserved ones
    S_new, Sv_new, Isv_new = add_m_cols(S, Sv, Ic, n2x)
    print("S_new:")
    print(S_new)
    print("Sv_new:")
    display_sv_new(Sv_new)
    print("Isv_new:")
    print(Isv_new)

    # Test Case 2: No Observed Columns (Only Unobserved)
    print("\nPython Test Case 2: No Observed Columns")
    S = np.array([]).reshape(0, 0)  # No observed data
    Sv = []  # No covariance for observed columns
    Ic = []  # No observed columns
    n2x = 3  # Total columns, all unobserved
    S_new, Sv_new, Isv_new = add_m_cols(S, Sv, Ic, n2x)
    print("S_new:")
    print(S_new)
    print("Sv_new:")
    display_sv_new(Sv_new)
    print("Isv_new:")
    print(Isv_new)

    # Test Case 3: All Columns Observed (No Unobserved Columns)
    print("\nPython Test Case 3: All Columns Observed")
    S = np.array([[5, 6, 7], [8, 9, 10]])  # Observed data for 3 columns
    Sv = [np.eye(2), np.eye(2), np.eye(2)]  # Covariance matrices for all columns
    Ic = [1, 2, 3]  # All columns observed
    n2x = 3  # Total columns match observed
    S_new, Sv_new, Isv_new = add_m_cols(S, Sv, Ic, n2x)
    print("S_new:")
    print(S_new)
    print("Sv_new:")
    display_sv_new(Sv_new)
    print("Isv_new:")
    print(Isv_new)

    # Test Case 4: Single Column Observed
    print("\nPython Test Case 4: Single Column Observed")
    S = np.array([[5], [6]])  # Observed data for a single column
    Sv = [np.eye(2)]  # Covariance matrix for the single observed column
    Ic = [2]  # Observed column at position 2
    n2x = 4  # Total columns, with unobserved columns at 1, 3, and 4
    S_new, Sv_new, Isv_new = add_m_cols(S, Sv, Ic, n2x)
    print("S_new:")
    print(S_new)
    print("Sv_new:")
    display_sv_new(Sv_new)
    print("Isv_new:")
    print(Isv_new)

# Run the tests
run_tests()


Python Test Case 1: Basic Case
S_new:
[[1. 0. 2. 0.]
 [3. 0. 4. 0.]]
Sv_new:
Column 1:
[[1. 0.]
 [0. 1.]]
Column 2:
[[1. 0.]
 [0. 1.]]
Column 3:
[[1. 0.]
 [0. 1.]]
Column 4:
[[1. 0.]
 [0. 1.]]
Isv_new:
[]

Python Test Case 2: No Observed Columns
S_new:
[]
Sv_new:
Column 1:
[]
Column 2:
[]
Column 3:
[]
Isv_new:
[]

Python Test Case 3: All Columns Observed
S_new:
[[ 5.  6.  7.]
 [ 8.  9. 10.]]
Sv_new:
Column 1:
[[1. 0.]
 [0. 1.]]
Column 2:
[[1. 0.]
 [0. 1.]]
Column 3:
[[1. 0.]
 [0. 1.]]
Isv_new:
[]

Python Test Case 4: Single Column Observed
S_new:
[[0. 5. 0. 0.]
 [0. 6. 0. 0.]]
Sv_new:
Column 1:
[[1. 0.]
 [0. 1.]]
Column 2:
[[1. 0.]
 [0. 1.]]
Column 3:
[[1. 0.]
 [0. 1.]]
Column 4:
[[1. 0.]
 [0. 1.]]
Isv_new:
[]


In [4]:
import numpy as np
from add_m_cols import add_m_cols


# Display function for Sv_new to match MATLAB structure
def display_sv_new(Sv_new):
    for idx, sv in enumerate(Sv_new, start=1):
        print(f"Column {idx}:")
        if isinstance(sv, np.ndarray):
            if sv.size > 0:
                print(sv)
            else:
                print('[]')
        else:
            print(sv)

def test_case_1():
    print("Python Test Case 1: Mixed Observed and Unobserved Columns")
    
    # Inputs
    S = np.array([[1, 2],
                  [3, 4]])  # Shape (2, 2)
    Sv = [np.eye(2), np.eye(2)]  # List of 2 covariance matrices
    Ic = [1, 3]  # Observed columns at positions 1 and 3
    n2x = 4  # Total columns
    Isv = [1, 2]  # Covariance indices for observed columns
    
    # Function call
    S_new, Sv_new, Isv_new = add_m_cols(S, Sv, Ic, n2x, Isv)
    
    # Outputs
    print("S_new:")
    print(S_new)
    
    print("\nSv_new:")
    display_sv_new(Sv_new)
    
    print("\nIsv_new:")
    print(Isv_new)

# Run Test Case 1
test_case_1()


Python Test Case 1: Mixed Observed and Unobserved Columns
S_new:
[[1. 0. 2. 0.]
 [3. 0. 4. 0.]]

Sv_new:
Column 1:
[[1. 0.]
 [0. 1.]]
Column 2:
[[1. 0.]
 [0. 1.]]
Column 3:
[[1. 0.]
 [0. 1.]]

Isv_new:
[1, 3, 2, 3]


In [5]:
import numpy as np
from add_m_cols import add_m_cols


# Display function for Sv_new to match MATLAB structure
def display_sv_new(Sv_new):
    for idx, sv in enumerate(Sv_new, start=1):
        print(f"Column {idx}:")
        if isinstance(sv, np.ndarray):
            if sv.size > 0:
                print(sv)
            else:
                print('[]')
        else:
            print(sv)

def test_case_2():
    print("\nPython Test Case 2: All Columns Observed")
    
    # Inputs
    S = np.array([[5, 6, 7],
                  [8, 9, 10]])  # Shape (2, 3)
    Sv = [np.eye(2), np.eye(2), np.eye(2)]  # List of 3 covariance matrices
    Ic = [1, 2, 3]  # All columns observed
    n2x = 3  # Total columns
    Isv = [1, 2, 3]  # Covariance indices for observed columns
    
    # Function call
    S_new, Sv_new, Isv_new = add_m_cols(S, Sv, Ic, n2x, Isv)
    
    # Outputs
    print("S_new:")
    print(S_new)
    
    print("\nSv_new:")
    display_sv_new(Sv_new)
    
    print("\nIsv_new:")
    print(Isv_new)

# Run Test Case 2
test_case_2()



Python Test Case 2: All Columns Observed
S_new:
[[ 5.  6.  7.]
 [ 8.  9. 10.]]

Sv_new:
Column 1:
[[1. 0.]
 [0. 1.]]
Column 2:
[[1. 0.]
 [0. 1.]]
Column 3:
[[1. 0.]
 [0. 1.]]
Column 4:
[[1. 0.]
 [0. 1.]]

Isv_new:
[1, 2, 3]
