In [1]:
import sys
import os
sys.path.append(os.path.abspath("../../src/vbpca_py"))

from pca_full import init_parms 

In [2]:
# Test 1 out of 6: Initialize Parameters with Random Initialization
import numpy as np

# Set random seed for reproducibility
np.random.seed(0)


# Define input parameters
init = 'random'
n1 = 3
n2 = 4
ncomp = 2
nobscomb = 3
Isv = [1, 2, 3]

# Call the init_parms function
A, S, Mu, V, Av, Sv, Muv = init_parms(init, n1, n2, ncomp, nobscomb, Isv)

# Display the outputs
print("A =")
print(A)

print("\nS =")
print(S)

print("\nMu =")
print(Mu)

print("\nV =")
print(V)

print("\nAv =")
for idx, av in enumerate(Av, start=1):
    print(f"Av[{idx}] =")
    print(av)

print("\nSv =")
for idx, sv in enumerate(Sv, start=1):
    print(f"Sv[{idx}] =")
    print(sv)

print("\nMuv =")
print(Muv)


in init_parms
A =
[[-0.61120516  0.20473766]
 [-0.67424345 -0.64059091]
 [-0.4145166   0.74008498]]

S =
[[ 0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502]]

Mu =
[]

V =
1

Av =
Av[1] =
[[1. 0.]
 [0. 1.]]
Av[2] =
[[1. 0.]
 [0. 1.]]
Av[3] =
[[1. 0.]
 [0. 1.]]

Sv =
Sv[1] =
[[1. 0.]
 [0. 1.]]
Sv[2] =
[[1. 0.]
 [0. 1.]]
Sv[3] =
[[1. 0.]
 [0. 1.]]

Muv =
[[1.]
 [1.]
 [1.]]


In [3]:
# Test 2 out of 6: Initialize Parameters with Provided Struct Values

import numpy as np
from scipy.linalg import orth
import numpy as np

# Set random seed for reproducibility
np.random.seed(0)

# Define input struct (as a dictionary in Python)
init = {
    "A": np.array([[1, 0], [0, 1], [1, 1]]),
    "Mu": np.array([1, 2, 3])
}

# Define input parameters
n1 = 3
n2 = 4
ncomp = 2
nobscomb = 2
Isv = [1, 1]

# Call the init_parms function
A, S, Mu, V, Av, Sv, Muv = init_parms(init, n1, n2, ncomp, nobscomb, Isv)

# Display the outputs
print("A =")
print(A)

print("\nS =")
print(S)

print("\nMu =")
print(Mu)

print("\nV =")
print(V)

print("\nAv =")
for idx, av in enumerate(Av, start=1):
    print(f"Av[{idx}] =")
    print(av)

print("\nSv =")
for idx, sv in enumerate(Sv, start=1):
    print(f"Sv[{idx}] =")
    print(sv)

print("\nMuv =")
print(Muv)


in init_parms
A =
[[1 0]
 [0 1]
 [1 1]]

S =
[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]]

Mu =
[1 2 3]

V =
1

Av =
Av[1] =
[[1. 0.]
 [0. 1.]]
Av[2] =
[[1. 0.]
 [0. 1.]]
Av[3] =
[[1. 0.]
 [0. 1.]]

Sv =
Sv[1] =
[[1. 0.]
 [0. 1.]]
Sv[2] =
[[1. 0.]
 [0. 1.]]

Muv =
[[1.]
 [1.]
 [1.]]


In [4]:
# Test 3 out of 6: Edge Case with ncomp Larger Than n1

import numpy as np
from scipy.linalg import orth

# Set random seed for reproducibility
np.random.seed(0)

# Define input parameters
init = 'random'
n1 = 2
n2 = 4
ncomp = 3
nobscomb = 2
Isv = [1, 2]

# Call the init_parms function
A, S, Mu, V, Av, Sv, Muv = init_parms(init, n1, n2, ncomp, nobscomb, Isv)

# Display the outputs
print("A =")
print(A)

print("\nS =")
print(S)

print("\nMu =")
print(Mu)

print("\nV =")
print(V)

print("\nAv =")
for idx, av in enumerate(Av, start=1):
    print(f"Av[{idx}] =")
    print(av)

print("\nSv =")
for idx, sv in enumerate(Sv, start=1):
    print(f"Sv[{idx}] =")
    print(sv)

print("\nMuv =")
print(Muv)


in init_parms
A =
[[-0.46208501 -0.88683564]
 [-0.88683564  0.46208501]]

S =
[[ 0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502]
 [ 0.44386323  0.33367433  1.49407907 -0.20515826]]

Mu =
[]

V =
1

Av =
Av[1] =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Av[2] =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Sv =
Sv[1] =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Sv[2] =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Muv =
[[1.]
 [1.]]


In [5]:
# Test 4 out of 6: Av Provided as a Matrix

import numpy as np
from scipy.linalg import orth

# Set random seed for reproducibility
np.random.seed(0)

# Define input struct (as a dictionary in Python)
init = {
    "Av": np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix
}

# Define other input parameters
n1 = 2
n2 = 3
ncomp = 2
nobscomb = 2
Isv = [1, 2]

# Call the init_parms function
A, S, Mu, V, Av, Sv, Muv = init_parms(init, n1, n2, ncomp, nobscomb, Isv)

# Display the outputs
print("A =")
print(A)

print("\nS =")
print(S)

print("\nMu =")
print(Mu)

print("\nV =")
print(V)

print("\nAv =")
for idx, av in enumerate(Av, start=1):
    print(f"Av[{idx}] =")
    print(av)

print("\nSv =")
for idx, sv in enumerate(Sv, start=1):
    print(f"Sv[{idx}] =")
    print(sv)

print("\nMuv =")
print(Muv)


in init_parms
A =
[[-0.52029037 -0.85398942]
 [-0.85398942  0.52029037]]

S =
[[ 1.86755799 -0.97727788  0.95008842]
 [-0.15135721 -0.10321885  0.4105985 ]]

Mu =
[]

V =
1

Av =
Av[1] =
[[1 0 0]
 [0 2 0]
 [0 0 3]]
Av[2] =
[[4 0 0]
 [0 5 0]
 [0 0 6]]

Sv =
Sv[1] =
[[1. 0.]
 [0. 1.]]
Sv[2] =
[[1. 0.]
 [0. 1.]]

Muv =
[[1.]
 [1.]]


In [6]:
# Test 5 out of 6: Sv Handling Multiple Observations

import numpy as np
from scipy.linalg import orth

# Set random seed for reproducibility
np.random.seed(0)

# Define input struct (as a dictionary in Python)
init = {
    "Sv": np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix for two observations
}

# Define other input parameters
n1 = 2
n2 = 3
ncomp = 2
nobscomb = 2
Isv = [0, 0, 1]  # Mapping of indices to observations

# Call the init_parms function
A, S, Mu, V, Av, Sv, Muv = init_parms(init, n1, n2, ncomp, nobscomb, Isv)

# Display the outputs
print("A =")
print(A)

print("\nS =")
print(S)

print("\nMu =")
print(Mu)

print("\nV =")
print(V)

print("\nAv =")
for idx, av in enumerate(Av, start=1):
    print(f"Av[{idx}] =")
    print(av)

print("\nSv =")
for idx, sv in enumerate(Sv, start=1):
    print(f"Sv[{idx}] =")
    print(sv)

print("\nMuv =")
print(Muv)


in init_parms
A =
[[-0.52029037 -0.85398942]
 [-0.85398942  0.52029037]]

S =
[[ 1.86755799 -0.97727788  0.95008842]
 [-0.15135721 -0.10321885  0.4105985 ]]

Mu =
[]

V =
1

Av =
Av[1] =
[[1. 0.]
 [0. 1.]]
Av[2] =
[[1. 0.]
 [0. 1.]]

Sv =
Sv[1] =
[[1 0]
 [0 4]]
Sv[2] =
[[2 0]
 [0 5]]

Muv =
[[1.]
 [1.]]


In [7]:
# Test 6 out of 6: All Parameters Missing in init

import numpy as np
from scipy.linalg import orth

# Set random seed for reproducibility
np.random.seed(0)

# Define an empty input dictionary
init = {}

# Define other input parameters
n1 = 2
n2 = 3
ncomp = 2
nobscomb = 2
Isv = [1, 2]

# Call the init_parms function
A, S, Mu, V, Av, Sv, Muv = init_parms(init, n1, n2, ncomp, nobscomb, Isv)

# Display the outputs
print("A =")
print(A)

print("\nS =")
print(S)

print("\nMu =")
print(Mu)

print("\nV =")
print(V)

print("\nAv =")
for idx, av in enumerate(Av, start=1):
    print(f"Av[{idx}] =")
    print(av)

print("\nSv =")
for idx, sv in enumerate(Sv, start=1):
    print(f"Sv[{idx}] =")
    print(sv)

print("\nMuv =")
print(Muv)


in init_parms
A =
[[-0.52029037 -0.85398942]
 [-0.85398942  0.52029037]]

S =
[[ 1.86755799 -0.97727788  0.95008842]
 [-0.15135721 -0.10321885  0.4105985 ]]

Mu =
[]

V =
1

Av =
Av[1] =
[[1. 0.]
 [0. 1.]]
Av[2] =
[[1. 0.]
 [0. 1.]]

Sv =
Sv[1] =
[[1. 0.]
 [0. 1.]]
Sv[2] =
[[1. 0.]
 [0. 1.]]

Muv =
[[1.]
 [1.]]


In [8]:
import numpy as np
from scipy.linalg import orth

# Set random seed for reproducibility
np.random.seed(0)

# Define Sv as a matrix with two rows and three columns
init = {
    "Sv": np.array([
        [1, 2, 3],  # First row
        [4, 5, 6]   # Second row
    ])
}

# Define other parameters
n1 = 2
n2 = 3  # Number of columns in Sv
ncomp = 2
nobscomb = 3  # nobscomb >= n2
Isv = [0, 1, 2]  # Mapping columns directly (Python 0-based indexing)

# Initialize Sv as a list of diagonal matrices
Sv = [np.diag(init["Sv"][:, i]) for i in range(n2)]

# Display the outputs
for idx, sv in enumerate(Sv, start=1):
    print(f"Sv[{idx}] =\n{sv}\n")


Sv[1] =
[[1 0]
 [0 4]]

Sv[2] =
[[2 0]
 [0 5]]

Sv[3] =
[[3 0]
 [0 6]]



In [9]:
# Test: Sv as a List with Isv Mapping

import numpy as np

# Define Sv as a list of diagonal matrices
init = {
    "Sv": [np.diag([1, 4]), np.diag([2, 5]), np.diag([3, 6])]
}

# Define other input parameters
n1 = 2
n2 = 3
ncomp = 2
nobscomb = 3
Isv = [0, 1, 2]  # Mapping based on Python's 0-based indexing

# Call the init_parms function
A, S, Mu, V, Av, Sv, Muv = init_parms(init, n1, n2, ncomp, nobscomb, Isv)

# Display the Sv matrices
for idx, sv in enumerate(Sv, start=1):
    print(f"Sv[{idx}] =\n{sv}\n")


in init_parms
Sv[1] =
[[1 0]
 [0 4]]

Sv[2] =
[[2 0]
 [0 5]]

Sv[3] =
[[3 0]
 [0 6]]

