In [1]:
import sys
import os
sys.path.append(os.path.abspath("../../src/vbpca_py"))

from pca_full import rotate_to_pca


In [2]:
import numpy as np
import scipy.io
import os


# Load MATLAB data and run the test using the rotate_to_pca function
def test_with_matlab_data():
    data_folder = 'data_rotateToPCA_test'
    os.makedirs(data_folder, exist_ok=True)
    data_file = os.path.join(data_folder, 'test_data.mat')

    # Load the test data from the .mat file in the specified folder
    data = scipy.io.loadmat(data_file)
    # Extract variables
    A = data['A']
    S = data['S']
    Av = [data['Av'][0, i] for i in range(data['Av'].shape[1])]
    Sv = [data['Sv'][0, i] for i in range(data['Sv'].shape[1])]
    Isv = data['Isv'][0] if 'Isv' in data and data['Isv'].size > 0 else []
    obscombj = [np.array([j[0]]) for j in data['obscombj'][0]]
    update_bias = bool(data['update_bias'][0, 0])

    # Run RotateToPCA
    dMu, A_rot, Av_rot, S_rot, Sv_rot = rotate_to_pca(A, Av, S, Sv, Isv, obscombj, update_bias)

    # Display results
    print('--- Test Using MATLAB Data ---')
    print('dMu:')
    print(dMu)
    print('A_rot:')
    print(A_rot)
    print('S_rot:')
    print(S_rot)
    print('Av_rot:')
    for i, Av_i in enumerate(Av_rot):
        print(f'Av_rot[{i}]:')
        print(Av_i)
    print('Sv_rot:')
    for j, Sv_j in enumerate(Sv_rot):
        print(f'Sv_rot[{j}]:')
        print(Sv_j)

# Run the test
test_with_matlab_data()


in rotate to pca
--- Test Using MATLAB Data ---
dMu:
[[-1.39613115]
 [-0.47694188]
 [ 0.38373862]
 [ 3.80064773]
 [ 2.94439624]]
A_rot:
[[-2.58087389  0.27520175]
 [-2.19728427  1.79742028]
 [ 2.39240267 -2.25476048]
 [ 5.17157633  1.65165381]
 [ 4.28483833  0.91912678]]
S_rot:
[[ 1.24347195 -0.70739872 -0.78466303  0.2485898 ]
 [-0.32393803  0.15590891  0.08481159  0.08321753]]
Av_rot:
Av_rot[0]:
[[ 3.34767461 -0.48519281]
 [-0.48519281  1.10749376]]
Av_rot[1]:
[[ 3.34767461 -0.48519281]
 [-0.48519281  1.10749376]]
Av_rot[2]:
[[ 3.34767461 -0.48519281]
 [-0.48519281  1.10749376]]
Av_rot[3]:
[[ 3.34767461 -0.48519281]
 [-0.48519281  1.10749376]]
Av_rot[4]:
[[ 3.34767461 -0.48519281]
 [-0.48519281  1.10749376]]
Sv_rot:
Sv_rot[0]:
[[0.3189679  0.13973978]
 [0.13973978 0.9641596 ]]
Sv_rot[1]:
[[0.3189679  0.13973978]
 [0.13973978 0.9641596 ]]
Sv_rot[2]:
[[0.3189679  0.13973978]
 [0.13973978 0.9641596 ]]
Sv_rot[3]:
[[0.3189679  0.13973978]
 [0.13973978 0.9641596 ]]


In [3]:
import numpy as np
import scipy.io

import os

# Define the path to the data file in the specified folder
data_folder = 'data_rotateToPCA_test'
mat_filename = os.path.join(data_folder, 'test_data_NcompOne_9683.mat')  # Replace XXXX with the unique number

def test_rotate_to_pca_ncomp_one():
    # Load the test data from the .mat file
    data = scipy.io.loadmat(mat_filename)
    
    # Extract variables
    A = data['A']
    S = data['S']
    Av = [data['Av'][0, i] for i in range(data['Av'].shape[1])]
    Sv = [data['Sv'][0, i] for i in range(data['Sv'].shape[1])]
    Isv = data['Isv'][0] if data['Isv'].size > 0 else []
    obscombj = [np.array([j[0]]) for j in data['obscombj'][0]]
    update_bias = bool(data['update_bias'][0, 0])

    # Expected results from MATLAB
    expected_dMu = data['dMu']
    expected_A_rot = data['A_rot']
    expected_Av_rot = [data['Av_rot'][0, i] for i in range(data['Av_rot'].shape[1])]
    expected_S_rot = data['S_rot']
    expected_Sv_rot = [data['Sv_rot'][0, i] for i in range(data['Sv_rot'].shape[1])]

    # Run the rotate_to_pca function with the loaded data
    dMu, A_rot, Av_rot, S_rot, Sv_rot = rotate_to_pca(A, Av, S, Sv, Isv, obscombj, update_bias)

    # Compare each result to the expected values from MATLAB
    print("--- Test Ncomp One ---")

    # Compare dMu
    print("dMu match:", np.allclose(dMu, expected_dMu, atol=1e-4))
    print("Python dMu:\n", dMu)
    print("MATLAB dMu:\n", expected_dMu)

    # Compare A_rot
    print("\nA_rot match:", np.allclose(A_rot, expected_A_rot, atol=1e-4))
    print("Python A_rot:\n", A_rot)
    print("MATLAB A_rot:\n", expected_A_rot)

    # Compare S_rot
    print("\nS_rot match:", np.allclose(S_rot, expected_S_rot, atol=1e-4))
    print("Python S_rot:\n", S_rot)
    print("MATLAB S_rot:\n", expected_S_rot)

    # Compare Av_rot
    print("\nAv_rot match:")
    for i, (actual, expected) in enumerate(zip(Av_rot, expected_Av_rot)):
        match = np.allclose(actual, expected, atol=1e-4)
        print(f"  Av_rot[{i}] match:", match)
        print("  Python Av_rot:\n", actual)
        print("  MATLAB Av_rot:\n", expected)

    # Compare Sv_rot
    print("\nSv_rot match:")
    for j, (actual, expected) in enumerate(zip(Sv_rot, expected_Sv_rot)):
        match = np.allclose(actual, expected, atol=1e-4)
        print(f"  Sv_rot[{j}] match:", match)
        print("  Python Sv_rot:\n", actual)
        print("  MATLAB Sv_rot:\n", expected)

# Run the test
test_rotate_to_pca_ncomp_one()


in rotate to pca
--- Test Ncomp One ---
dMu match: True
Python dMu:
 [[ 0.29299379]
 [ 0.99934863]
 [-1.23092533]
 [ 0.46982865]
 [ 0.17370642]]
MATLAB dMu:
 [[ 0.29299379]
 [ 0.99934863]
 [-1.23092533]
 [ 0.46982865]
 [ 0.17370642]]

A_rot match: True
Python A_rot:
 [[ 1.12886251]
 [ 3.85034511]
 [-4.74257649]
 [ 1.81018155]
 [ 0.66926561]]
MATLAB A_rot:
 [[ 1.12886251]
 [ 3.85034511]
 [-4.74257649]
 [ 1.81018155]
 [ 0.66926561]]

S_rot match: True
Python S_rot:
 [[-0.88238807 -0.46606382 -0.09635883  1.44481072]]
MATLAB S_rot:
 [[-0.88238807 -0.46606382 -0.09635883  1.44481072]]

Av_rot match:
  Av_rot[0] match: True
  Python Av_rot:
 [[4.40813728]]
  MATLAB Av_rot:
 [[4.40813728]]
  Av_rot[1] match: True
  Python Av_rot:
 [[4.40813728]]
  MATLAB Av_rot:
 [[4.40813728]]
  Av_rot[2] match: True
  Python Av_rot:
 [[4.40813728]]
  MATLAB Av_rot:
 [[4.40813728]]
  Av_rot[3] match: True
  Python Av_rot:
 [[4.40813728]]
  MATLAB Av_rot:
 [[4.40813728]]
  Av_rot[4] match: True
  Python Av_r

In [4]:
import numpy as np
import scipy.io

import os

# Define the path to the data file in the specified folder
data_folder = 'data_rotateToPCA_test'
mat_filename = os.path.join(data_folder, 'test_data_EmptyIsv_8129.mat')  # Replace XXXX with the unique number

def test_rotate_to_pca_empty_isv():
    # Load the test data from the .mat file
    data = scipy.io.loadmat(mat_filename)
    
    # Extract variables
    A = data['A']
    S = data['S']
    Av = [data['Av'][0, i] for i in range(data['Av'].shape[1])]
    Sv = [data['Sv'][0, i] for i in range(data['Sv'].shape[1])]
    Isv = data['Isv'][0] if data['Isv'].size > 0 else []
    obscombj = [np.array([j[0]]) for j in data['obscombj'][0]]
    update_bias = bool(data['update_bias'][0, 0])

    # Expected results from MATLAB
    expected_dMu = data['dMu']
    expected_A_rot = data['A_rot']
    expected_Av_rot = [data['Av_rot'][0, i] for i in range(data['Av_rot'].shape[1])]
    expected_S_rot = data['S_rot']
    expected_Sv_rot = [data['Sv_rot'][0, i] for i in range(data['Sv_rot'].shape[1])]

    # Run the rotate_to_pca function with the loaded data
    dMu, A_rot, Av_rot, S_rot, Sv_rot = rotate_to_pca(A, Av, S, Sv, Isv, obscombj, update_bias)

    # Compare each result to the expected values from MATLAB
    print("--- Test Empty Isv ---")

    # Compare dMu
    print("dMu match:", np.allclose(dMu, expected_dMu, atol=1e-4))
    print("Python dMu:\n", dMu)
    print("MATLAB dMu:\n", expected_dMu)

    # Compare A_rot
    print("\nA_rot match:", np.allclose(A_rot, expected_A_rot, atol=1e-4))
    print("Python A_rot:\n", A_rot)
    print("MATLAB A_rot:\n", expected_A_rot)

    # Compare S_rot
    print("\nS_rot match:", np.allclose(S_rot, expected_S_rot, atol=1e-4))
    print("Python S_rot:\n", S_rot)
    print("MATLAB S_rot:\n", expected_S_rot)

    # Compare Av_rot
    print("\nAv_rot match:")
    for i, (actual, expected) in enumerate(zip(Av_rot, expected_Av_rot)):
        match = np.allclose(actual, expected, atol=1e-4)
        print(f"  Av_rot[{i}] match:", match)
        print("  Python Av_rot:\n", actual)
        print("  MATLAB Av_rot:\n", expected)

    # Compare Sv_rot
    print("\nSv_rot match:")
    for j, (actual, expected) in enumerate(zip(Sv_rot, expected_Sv_rot)):
        match = np.allclose(actual, expected, atol=1e-4)
        print(f"  Sv_rot[{j}] match:", match)
        print("  Python Sv_rot:\n", actual)
        print("  MATLAB Sv_rot:\n", expected)

# Run the test
test_rotate_to_pca_empty_isv()


in rotate to pca
--- Test Empty Isv ---
dMu match: True
Python dMu:
 [[-1.39613115]
 [-0.47694188]
 [ 0.38373862]
 [ 3.80064773]
 [ 2.94439624]]
MATLAB dMu:
 [[-1.39613115]
 [-0.47694188]
 [ 0.38373862]
 [ 3.80064773]
 [ 2.94439624]]

A_rot match: True
Python A_rot:
 [[-2.58087389  0.27520175]
 [-2.19728427  1.79742028]
 [ 2.39240267 -2.25476048]
 [ 5.17157633  1.65165381]
 [ 4.28483833  0.91912678]]
MATLAB A_rot:
 [[-2.58087389  0.27520175]
 [-2.19728427  1.79742028]
 [ 2.39240267 -2.25476048]
 [ 5.17157633  1.65165381]
 [ 4.28483833  0.91912678]]

S_rot match: True
Python S_rot:
 [[ 1.24347195 -0.70739872 -0.78466303  0.2485898 ]
 [-0.32393803  0.15590891  0.08481159  0.08321753]]
MATLAB S_rot:
 [[ 1.24347195 -0.70739872 -0.78466303  0.2485898 ]
 [-0.32393803  0.15590891  0.08481159  0.08321753]]

Av_rot match:
  Av_rot[0] match: True
  Python Av_rot:
 [[ 3.34767461 -0.48519281]
 [-0.48519281  1.10749376]]
  MATLAB Av_rot:
 [[ 3.34767461 -0.48519281]
 [-0.48519281  1.10749376]]
  Av_

In [5]:
import numpy as np
import scipy.io

import os

# Define the path to the data file in the specified folder
data_folder = 'data_rotateToPCA_test'
mat_filename = os.path.join(data_folder, 'test_data_NonEmptyIsv.mat')  # Replace XXXX with the unique number

def test_rotate_to_pca_non_empty_isv():
    # Load the test data from the .mat file
    data = scipy.io.loadmat(mat_filename)
    
    # Extract variables
    A = data['A']
    S = data['S']
    Av = [data['Av'][0, i] for i in range(data['Av'].shape[1])]
    Sv = [data['Sv'][0, i] for i in range(data['Sv'].shape[1])]
    Isv = data['Isv'][0] if data['Isv'].size > 0 else []
    obscombj = [np.array(data['obscombj'][0, i].flatten()) for i in range(data['obscombj'].shape[1])]
    update_bias = bool(data['update_bias'][0, 0])

    # Expected results from MATLAB
    expected_dMu = data['dMu']
    expected_A_rot = data['A_rot']
    expected_Av_rot = [data['Av_rot'][0, i] for i in range(data['Av_rot'].shape[1])]
    expected_S_rot = data['S_rot']
    expected_Sv_rot = [data['Sv_rot'][0, i] for i in range(data['Sv_rot'].shape[1])]

    # Run the rotate_to_pca function with the loaded data
    dMu, A_rot, Av_rot, S_rot, Sv_rot = rotate_to_pca(A, Av, S, Sv, Isv, obscombj, update_bias)

    # Compare each result to the expected values from MATLAB
    print("--- Test Non-Empty Isv ---")

    # Compare dMu
    print("dMu match:", np.allclose(dMu, expected_dMu, atol=1e-4))
    print("Python dMu:\n", dMu)
    print("MATLAB dMu:\n", expected_dMu)

    # Compare A_rot
    print("\nA_rot match:", np.allclose(A_rot, expected_A_rot, atol=1e-4))
    print("Python A_rot:\n", A_rot)
    print("MATLAB A_rot:\n", expected_A_rot)

    # Compare S_rot
    print("\nS_rot match:", np.allclose(S_rot, expected_S_rot, atol=1e-4))
    print("Python S_rot:\n", S_rot)
    print("MATLAB S_rot:\n", expected_S_rot)

    # Compare Av_rot
    print("\nAv_rot match:")
    for i, (actual, expected) in enumerate(zip(Av_rot, expected_Av_rot)):
        match = np.allclose(actual, expected, atol=1e-4)
        print(f"  Av_rot[{i}] match:", match)
        print("  Python Av_rot:\n", actual)
        print("  MATLAB Av_rot:\n", expected)

    # Compare Sv_rot
    print("\nSv_rot match:")
    for j, (actual, expected) in enumerate(zip(Sv_rot, expected_Sv_rot)):
        match = np.allclose(actual, expected, atol=1e-4)
        print(f"  Sv_rot[{j}] match:", match)
        print("  Python Sv_rot:\n", actual)
        print("  MATLAB Sv_rot:\n", expected)

# Run the test
test_rotate_to_pca_non_empty_isv()


in rotate to pca
--- Test Non-Empty Isv ---
dMu match: True
Python dMu:
 [[-1.39613115]
 [-0.47694188]
 [ 0.38373862]
 [ 3.80064773]
 [ 2.94439624]]
MATLAB dMu:
 [[-1.39613115]
 [-0.47694188]
 [ 0.38373862]
 [ 3.80064773]
 [ 2.94439624]]

A_rot match: True
Python A_rot:
 [[-2.58087389  0.27520175]
 [-2.19728427  1.79742028]
 [ 2.39240267 -2.25476048]
 [ 5.17157633  1.65165381]
 [ 4.28483833  0.91912678]]
MATLAB A_rot:
 [[-2.58087389  0.27520175]
 [-2.19728427  1.79742028]
 [ 2.39240267 -2.25476048]
 [ 5.17157633  1.65165381]
 [ 4.28483833  0.91912678]]

S_rot match: True
Python S_rot:
 [[ 1.24347195 -0.70739872 -0.78466303  0.2485898 ]
 [-0.32393803  0.15590891  0.08481159  0.08321753]]
MATLAB S_rot:
 [[ 1.24347195 -0.70739872 -0.78466303  0.2485898 ]
 [-0.32393803  0.15590891  0.08481159  0.08321753]]

Av_rot match:
  Av_rot[0] match: True
  Python Av_rot:
 [[ 3.34767461 -0.48519281]
 [-0.48519281  1.10749376]]
  MATLAB Av_rot:
 [[ 3.34767461 -0.48519281]
 [-0.48519281  1.10749376]]
 

In [6]:
import numpy as np
import scipy.io

import os

# Define the path to the data file in the specified folder
data_folder = 'data_rotateToPCA_test'
mat_filename = os.path.join(data_folder, 'test_data_NoVarianceMatrices.mat')

def test_rotate_to_pca_no_variance_matrices():
    # Load the test data from the .mat file
    data = scipy.io.loadmat(mat_filename)
    
    # Extract variables
    A = data['A']
    S = data['S']
    Av = []  # Explicitly set empty list for Av
    Sv = []  # Explicitly set empty list for Sv
    Isv = data['Isv'][0] if data['Isv'].size > 0 else []
    obscombj = [np.array([j[0]]) for j in data['obscombj'][0]]
    update_bias = bool(data['update_bias'][0, 0])

    # Expected behavior: Catch an error when Av and Sv are empty
    print("--- Test No Variance Matrices ---")
    try:
        # Attempt to run the rotate_to_pca function with empty Av and Sv
        dMu, A_rot, Av_rot, S_rot, Sv_rot = rotate_to_pca(A, Av, S, Sv, Isv, obscombj, update_bias)
        print("Error: Function did not raise an error as expected.")
    except Exception as e:
        # Print expected error message
        print("Expected Error Caught:")
        print(e)

# Run the test
test_rotate_to_pca_no_variance_matrices()


--- Test No Variance Matrices ---
in rotate to pca
Expected Error Caught:
list index out of range


In [7]:
import numpy as np
import scipy.io
import os


# Define the path to the data file in the specified folder
data_folder = 'data_rotateToPCA_test'
mat_filename = os.path.join(data_folder, 'test_data_LargeMatrices.mat')

def test_rotate_to_pca_large_matrices():
    # Load the test data from the .mat file
    data = scipy.io.loadmat(mat_filename)
    # Define the matrix dimensions and number of components
    n1 = 100
    n2 = 80
    ncomp = 10

    # Extract variables
    A = data['A']
    S = data['S']
    Av = [data['Av'][0, i] for i in range(data['Av'].shape[1])]
    Sv = [data['Sv'][0, i] for i in range(data['Sv'].shape[1])]
    Isv = data['Isv'][0] if data['Isv'].size > 0 else []
    obscombj = [np.array([j[0]]) for j in data['obscombj'][0]]
    update_bias = bool(data['update_bias'][0, 0])

    # Expected results from MATLAB
    expected_dMu = data['dMu']
    expected_A_rot = data['A_rot']
    expected_Av_rot = [data['Av_rot'][0, i] for i in range(data['Av_rot'].shape[1])]
    expected_S_rot = data['S_rot']
    expected_Sv_rot = [data['Sv_rot'][0, i] for i in range(data['Sv_rot'].shape[1])]

    # Run the rotate_to_pca function with the loaded data
    dMu, A_rot, Av_rot, S_rot, Sv_rot = rotate_to_pca(A, Av, S, Sv, Isv, obscombj, update_bias)

    # Display summary of results for comparison
    print("--- Test Large Matrices ---")
    
    # dMu summary
    print("dMu Summary - Python: Min =", np.min(dMu), "Max =", np.max(dMu))
    print("dMu Summary - MATLAB: Min =", np.min(expected_dMu), "Max =", np.max(expected_dMu))
    print("dMu match:", np.allclose(dMu, expected_dMu, atol=1e-4))

    # Check dimensions of A_rot and S_rot
    print("\nA_rot dimensions match:", A_rot.shape == expected_A_rot.shape)
    print("S_rot dimensions match:", S_rot.shape == expected_S_rot.shape)

    # Av_rot trace summaries
    print("\nAv_rot Summary:")
    for i, (actual, expected) in enumerate(zip(Av_rot, expected_Av_rot)):
        print(f"  Av_rot[{i}] Trace - Python:", np.trace(actual), "MATLAB:", np.trace(expected))

    # Sv_rot trace summaries
    print("\nSv_rot Summary:")
    for j, (actual, expected) in enumerate(zip(Sv_rot, expected_Sv_rot)):
        print(f"  Sv_rot[{j}] Trace - Python:", np.trace(actual), "MATLAB:", np.trace(expected))

    # Basic checks on dimensions
    if A_rot.shape == (n1, ncomp) and S_rot.shape == (ncomp, n2):
        print("\nSuccess: Rotated matrices have correct dimensions.")
    else:
        print("\nFailure: Rotated matrices have incorrect dimensions.")

    # Check for NaNs
    if not np.isnan(A_rot).any() and not np.isnan(S_rot).any():
        print("Success: No NaN values in rotated matrices.")
    else:
        print("Failure: NaN values found in rotated matrices.")

# Run the test
test_rotate_to_pca_large_matrices()


in rotate to pca
--- Test Large Matrices ---
dMu Summary - Python: Min = -0.8826847657745234 Max = 0.8211474815462507
dMu Summary - MATLAB: Min = -0.8826847657745234 Max = 0.8211474815462508
dMu match: True

A_rot dimensions match: True
S_rot dimensions match: True

Av_rot Summary:
  Av_rot[0] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[1] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[2] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[3] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[4] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[5] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[6] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[7] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[8] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[9] Trace - Python: 19.969960489005064 MATLAB: 19.96

In [8]:
import numpy as np
import scipy.io
import os

# Define the path to the data file in the specified folder
data_folder = 'data_rotateToPCA_test'
mat_filename = os.path.join(data_folder, 'test_data_NoBiasUpdate.mat')

def test_rotate_to_pca_no_bias_update():
    # Load the test data from the .mat file
    data = scipy.io.loadmat(mat_filename)
    
    # Extract variables
    A = data['A']
    S = data['S']
    Av = [data['Av'][0, i] for i in range(data['Av'].shape[1])]
    Sv = [data['Sv'][0, i] for i in range(data['Sv'].shape[1])]
    Isv = data['Isv'][0] if data['Isv'].size > 0 else []
    obscombj = [np.array([j[0]]) for j in data['obscombj'][0]]
    update_bias = bool(data['update_bias'][0, 0])

    # Expected results from MATLAB
    expected_dMu = data['dMu']
    expected_A_rot = data['A_rot']
    expected_Av_rot = [data['Av_rot'][0, i] for i in range(data['Av_rot'].shape[1])]
    expected_S_rot = data['S_rot']
    expected_Sv_rot = [data['Sv_rot'][0, i] for i in range(data['Sv_rot'].shape[1])]

    # Run the rotate_to_pca function with the loaded data
    dMu, A_rot, Av_rot, S_rot, Sv_rot = rotate_to_pca(A, Av, S, Sv, Isv, obscombj, update_bias)

    # Compare each result to the expected values from MATLAB
    print("--- Test No Bias Update ---")

    # Check if dMu is zero
    is_dMu_zero = np.all(dMu == 0)
    print("dMu is zero as expected:", is_dMu_zero)
    print("Python dMu:\n", dMu)
    print("MATLAB dMu:\n", expected_dMu)

    # Compare A_rot
    print("\nA_rot match:", np.allclose(A_rot, expected_A_rot, atol=1e-4))
    print("Python A_rot:\n", A_rot)
    print("MATLAB A_rot:\n", expected_A_rot)

    # Compare S_rot
    print("\nS_rot match:", np.allclose(S_rot, expected_S_rot, atol=1e-4))
    print("Python S_rot:\n", S_rot)
    print("MATLAB S_rot:\n", expected_S_rot)

    # Compare Av_rot
    print("\nAv_rot match:")
    for i, (actual, expected) in enumerate(zip(Av_rot, expected_Av_rot)):
        match = np.allclose(actual, expected, atol=1e-4)
        print(f"  Av_rot[{i}] match:", match)
        print("  Python Av_rot:\n", actual)
        print("  MATLAB Av_rot:\n", expected)

    # Compare Sv_rot
    print("\nSv_rot match:")
    for j, (actual, expected) in enumerate(zip(Sv_rot, expected_Sv_rot)):
        match = np.allclose(actual, expected, atol=1e-4)
        print(f"  Sv_rot[{j}] match:", match)
        print("  Python Sv_rot:\n", actual)
        print("  MATLAB Sv_rot:\n", expected)

# Run the test
test_rotate_to_pca_no_bias_update()


in rotate to pca
--- Test No Bias Update ---
dMu is zero as expected: True
Python dMu:
 0
MATLAB dMu:
 [[0]]

A_rot match: True
Python A_rot:
 [[-2.9140294   0.4407503 ]
 [-2.0366384   2.03429483]
 [ 2.13286791 -2.53094156]
 [ 6.46534374  1.45513418]
 [ 5.22905914  0.72872719]]
MATLAB A_rot:
 [[-2.9140294   0.4407503 ]
 [-2.0366384   2.03429483]
 [ 2.13286791 -2.53094156]
 [ 6.46534374  1.45513418]
 [ 5.22905914  0.72872719]]

S_rot match: True
Python S_rot:
 [[ 1.56628591 -0.07211913 -0.1411704   0.73825549]
 [-0.29567888  0.59517795  0.54668325  0.30967586]]
MATLAB S_rot:
 [[ 1.56628591 -0.07211913 -0.1411704   0.73825549]
 [-0.29567888  0.59517795  0.54668325  0.30967586]]

Av_rot match:
  Av_rot[0] match: True
  Python Av_rot:
 [[ 4.26962152 -0.47857079]
 [-0.47857079  1.3180339 ]]
  MATLAB Av_rot:
 [[ 4.26962152 -0.47857079]
 [-0.47857079  1.3180339 ]]
  Av_rot[1] match: True
  Python Av_rot:
 [[ 4.26962152 -0.47857079]
 [-0.47857079  1.3180339 ]]
  MATLAB Av_rot:
 [[ 4.26962152 -

In [9]:
import numpy as np
import scipy.io
import os

# Define the path to the data file in the specified folder
data_folder = 'data_rotateToPCA_test'
mat_filename = os.path.join(data_folder, 'test_data_LargeMatrices.mat')

def test_rotate_to_pca_large_matrices():
    # Load the test data from the .mat file
    data = scipy.io.loadmat(mat_filename)
    # Define the matrix dimensions and number of components
    n1 = 100
    n2 = 80
    ncomp = 10

    # Extract variables
    A = data['A']
    S = data['S']
    Av = [data['Av'][0, i] for i in range(data['Av'].shape[1])]
    Sv = [data['Sv'][0, i] for i in range(data['Sv'].shape[1])]
    Isv = data['Isv'][0] if data['Isv'].size > 0 else []
    obscombj = [np.array([j[0]]) for j in data['obscombj'][0]]
    update_bias = bool(data['update_bias'][0, 0])

    # Expected results from MATLAB
    expected_dMu = data['dMu']
    expected_A_rot = data['A_rot']
    expected_Av_rot = [data['Av_rot'][0, i] for i in range(data['Av_rot'].shape[1])]
    expected_S_rot = data['S_rot']
    expected_Sv_rot = [data['Sv_rot'][0, i] for i in range(data['Sv_rot'].shape[1])]

    # Run the rotate_to_pca function with the loaded data
    dMu, A_rot, Av_rot, S_rot, Sv_rot = rotate_to_pca(A, Av, S, Sv, Isv, obscombj, update_bias)

    # Display summary of results for comparison
    print("--- Test Large Matrices ---")
    
    # dMu summary
    print("dMu Summary - Python: Min =", np.min(dMu), "Max =", np.max(dMu))
    print("dMu Summary - MATLAB: Min =", np.min(expected_dMu), "Max =", np.max(expected_dMu))
    print("dMu match:", np.allclose(dMu, expected_dMu, atol=1e-4))

    # Check dimensions of A_rot and S_rot
    print("\nA_rot dimensions match:", A_rot.shape == expected_A_rot.shape)
    print("S_rot dimensions match:", S_rot.shape == expected_S_rot.shape)

    # Av_rot trace summaries
    print("\nAv_rot Summary:")
    for i, (actual, expected) in enumerate(zip(Av_rot, expected_Av_rot)):
        print(f"  Av_rot[{i}] Trace - Python:", np.trace(actual), "MATLAB:", np.trace(expected))

    # Sv_rot trace summaries
    print("\nSv_rot Summary:")
    for j, (actual, expected) in enumerate(zip(Sv_rot, expected_Sv_rot)):
        print(f"  Sv_rot[{j}] Trace - Python:", np.trace(actual), "MATLAB:", np.trace(expected))

    # Basic checks on dimensions
    if A_rot.shape == (n1, ncomp) and S_rot.shape == (ncomp, n2):
        print("\nSuccess: Rotated matrices have correct dimensions.")
    else:
        print("\nFailure: Rotated matrices have incorrect dimensions.")

    # Check for NaNs
    if not np.isnan(A_rot).any() and not np.isnan(S_rot).any():
        print("Success: No NaN values in rotated matrices.")
    else:
        print("Failure: NaN values found in rotated matrices.")

# Run the test
test_rotate_to_pca_large_matrices()


in rotate to pca
--- Test Large Matrices ---
dMu Summary - Python: Min = -0.8826847657745234 Max = 0.8211474815462507
dMu Summary - MATLAB: Min = -0.8826847657745234 Max = 0.8211474815462508
dMu match: True

A_rot dimensions match: True
S_rot dimensions match: True

Av_rot Summary:
  Av_rot[0] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[1] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[2] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[3] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[4] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[5] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[6] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[7] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[8] Trace - Python: 19.969960489005064 MATLAB: 19.96996048900508
  Av_rot[9] Trace - Python: 19.969960489005064 MATLAB: 19.96

In [10]:
import numpy as np

def test_rotate_to_pca_invalid_input_types():
    print("--- Test Invalid Input Types ---")

    # Initialize valid parameters for testing
    n1, n2, ncomp = 5, 4, 2
    np.random.seed(0)  # For reproducibility
    A = np.random.randn(n1, ncomp)
    S = np.random.randn(ncomp, n2)
    Av = [np.eye(ncomp) for _ in range(n1)]
    Sv = [np.eye(ncomp) for _ in range(n2)]
    Isv = []
    obscombj = [np.array([i]) for i in range(1, n2 + 1)]
    update_bias = True

    # Define a list of invalid inputs with descriptions
    invalid_inputs = [
        ("Invalid A", "invalid_A", Av, S, Sv, Isv, obscombj, update_bias, True),
        ("Invalid Av", A, "invalid_Av", S, Sv, Isv, obscombj, update_bias, True),
        ("Invalid S", A, Av, "invalid_S", Sv, Isv, obscombj, update_bias, True),
        ("Invalid Sv", A, Av, S, "invalid_Sv", Isv, obscombj, update_bias, True),
        ("Invalid Isv", A, Av, S, Sv, "invalid_Isv", obscombj, update_bias, False),
        ("Invalid obscombj", A, Av, S, Sv, Isv, "invalid_obscombj", update_bias, False),
        ("Invalid update_bias", A, Av, S, Sv, Isv, obscombj, "invalid_update_bias", False)
    ]

    # Test each invalid input case
    for description, test_A, test_Av, test_S, test_Sv, test_Isv, test_obscombj, test_update_bias, expect_error in invalid_inputs:
        print(f"Testing {description}...")
        try:
            # Attempt to run with invalid input
            dMu, A_rot, Av_rot, S_rot, Sv_rot = rotate_to_pca(
                test_A, test_Av, test_S, test_Sv, test_Isv, test_obscombj, test_update_bias
            )
            if expect_error:
                print(f"No Error: {description} did not throw an error as expected.\n")
            else:
                print(f"Success: {description} did not throw an error, matching MATLAB's behavior.\n")
        except Exception as e:
            if expect_error:
                # Expected error message
                print(f"Expected Error for {description}: {e}\n")
            else:
                print(f"Unexpected Error for {description}: {e}\n")

# Run the test
test_rotate_to_pca_invalid_input_types()


--- Test Invalid Input Types ---
Testing Invalid A...
in rotate to pca
Expected Error for Invalid A: 'str' object has no attribute 'shape'

Testing Invalid Av...
in rotate to pca
Expected Error for Invalid Av: ufunc 'matmul' did not contain a loop with signature matching types (dtype('float64'), dtype('<U1')) -> None

Testing Invalid S...
in rotate to pca
Expected Error for Invalid S: 'str' object has no attribute 'shape'

Testing Invalid Sv...
in rotate to pca
Expected Error for Invalid Sv: ufunc 'add' did not contain a loop with signature matching types (dtype('float64'), dtype('<U1')) -> None

Testing Invalid Isv...
in rotate to pca
Success: Invalid Isv did not throw an error, matching MATLAB's behavior.

Testing Invalid obscombj...
in rotate to pca
Success: Invalid obscombj did not throw an error, matching MATLAB's behavior.

Testing Invalid update_bias...
in rotate to pca
Success: Invalid update_bias did not throw an error, matching MATLAB's behavior.

