In [1]:
import sys
import os
sys.path.append(os.path.abspath("../../src/vbpca_py"))
from add_m_rows import add_m_rows

In [2]:
def display_av_new(Av_new):
    for idx, av in enumerate(Av_new, start=1):
        print(f"Row {idx}:")
        print(av if isinstance(av, np.ndarray) and av.size > 0 else '[]')


In [4]:

import numpy as np

def display_av_new(Av_new):
    for idx, av in enumerate(Av_new, start=1):
        print(f"Row {idx}:")
        print(av if isinstance(av, np.ndarray) and av.size > 0 else '[]')

# Test Case 1: Standard Case with Observed and Unobserved Rows
print("\nPython Test Case 1: Standard Case with Observed and Unobserved Rows")

# Existing parameter matrix A with 2 observed rows and 3 components
A = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

# Covariance information as a list (cell array in MATLAB)
Av = [
    np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]]),
    np.array([[2, 0, 0],
              [0, 2, 0],
              [0, 0, 2]])
]

# Observed row indices (1-based)
Ir = [1, 3]

# Total number of rows after addition
n1x = 4

# Variance of the prior for A
Va = [3, 3, 3]

# Call the function
A_new, Av_new = add_m_rows(A, Av, Ir, n1x, Va)

print("A_new:")
print(A_new)
print("\nAv_new:")
display_av_new(Av_new)



Python Test Case 1: Standard Case with Observed and Unobserved Rows
in add m rows
A_new:
[[1. 2. 3.]
 [0. 0. 0.]
 [4. 5. 6.]
 [0. 0. 0.]]

Av_new:
Row 1:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Row 2:
[[3 0 0]
 [0 3 0]
 [0 0 3]]
Row 3:
[[2 0 0]
 [0 2 0]
 [0 0 2]]
Row 4:
[[3 0 0]
 [0 3 0]
 [0 0 3]]


In [5]:
# Test Case 2: No Observed Rows (All Unobserved)

import numpy as np
# Test Case 2: No Observed Rows (All Unobserved)
print("\nPython Test Case 2: No Observed Rows (All Unobserved)")

# Existing parameter matrix A is empty (no observed rows)
A = np.array([]).reshape(0, 0)  # Shape: (0,0), ncomp=0

# Covariance information is empty
Av = []

# Observed row indices are empty
Ir = []

# Total number of rows after addition
n1x = 3

# Variance of the prior for A (defaults to inf if not provided)
Va = []  # Must match ncomp=0

# Call the function
A_new, Av_new = add_m_rows(A, Av, Ir, n1x, Va)

print("A_new:")
print(A_new)
print("\nAv_new:")
print(Av_new)




Python Test Case 2: No Observed Rows (All Unobserved)
in add m rows
A_new:
[]

Av_new:
[]


In [6]:
# Test Case 3: Mixed Observed Rows with Some Infinite Va

print("\nPython Test Case 3: Mixed Observed Rows with Some Infinite Va")

# Existing parameter matrix A with 1 observed row and 2 components
A = np.array([
    [7.0, 8.0]
])

# Covariance information as a list
Av = [
    np.array([[4, 0],
              [0, 4]])
]

# Observed row indices (1-based)
Ir = [2]

# Total number of rows after addition
n1x = 4

# Variance of the prior for A (some finite, some infinite)
Va = [5, np.inf]

# Call the function
A_new, Av_new = add_m_rows(A, Av, Ir, n1x, Va)

print("A_new:")
print(A_new)
print("\nAv_new:")
display_av_new(Av_new)



Python Test Case 3: Mixed Observed Rows with Some Infinite Va
in add m rows
A_new:
[[nan nan]
 [ 7.  8.]
 [nan nan]
 [nan nan]]

Av_new:
Row 1:
[[ 5.  0.]
 [ 0. inf]]
Row 2:
[[4 0]
 [0 4]]
Row 3:
[[ 5.  0.]
 [ 0. inf]]
Row 4:
[[ 5.  0.]
 [ 0. inf]]


In [7]:
import numpy as np

# Assuming add_m_rows and display_av_new are already defined as per previous corrections

# Test Case 4: All Rows Observed (No Unobserved Rows)
print("\nPython Test Case 4: All Rows Observed (No Unobserved Rows)")

# Existing parameter matrix A with 3 observed rows and 2 components
A = np.array([
    [10.0, 20.0],
    [30.0, 40.0],
    [50.0, 60.0]
])

# Covariance information as a list (cell array in MATLAB)
Av = [
    np.array([[1, 0],
              [0, 1]]),
    np.array([[2, 0],
              [0, 2]]),
    np.array([[3, 0],
              [0, 3]])
]

# Observed row indices (all rows)
Ir = [1, 2, 3]

# Total number of rows after addition (same as observed)
n1x = 3

# Variance of the prior for A
Va = [5, 5]  # Length matches ncomp=2

# Call the function
A_new, Av_new = add_m_rows(A, Av, Ir, n1x, Va)

print("A_new:")
print(A_new)
print("\nAv_new:")
display_av_new(Av_new)



Python Test Case 4: All Rows Observed (No Unobserved Rows)
in add m rows
A_new:
[[10. 20.]
 [30. 40.]
 [50. 60.]]

Av_new:
Row 1:
[[1 0]
 [0 1]]
Row 2:
[[2 0]
 [0 2]]
Row 3:
[[3 0]
 [0 3]]


In [8]:
# Test Case 5: Some Observed Rows with Finite and Infinite Va

print("\nPython Test Case 5: Some Observed Rows with Finite and Infinite Va")

# Existing parameter matrix A with 2 observed rows and 2 components
A = np.array([
    [15.0, 25.0],
    [35.0, 45.0]
])

# Covariance information as a list (cell array in MATLAB)
Av = [
    np.array([[1.5, 0],
              [0, 1.5]]),
    np.array([[2.5, 0],
              [0, 2.5]])
]

# Observed row indices (1-based)
Ir = [1, 3]

# Total number of rows after addition
n1x = 4

# Variance of the prior for A (mixed)
Va = [5, np.inf]  # First component finite, second component infinite

# Call the function
A_new, Av_new = add_m_rows(A, Av, Ir, n1x, Va)

print("A_new:")
print(A_new)
print("\nAv_new:")
display_av_new(Av_new)



Python Test Case 5: Some Observed Rows with Finite and Infinite Va
in add m rows
A_new:
[[15. 25.]
 [nan nan]
 [35. 45.]
 [nan nan]]

Av_new:
Row 1:
[[1.5 0. ]
 [0.  1.5]]
Row 2:
[[ 5.  0.]
 [ 0. inf]]
Row 3:
[[2.5 0. ]
 [0.  2.5]]
Row 4:
[[ 5.  0.]
 [ 0. inf]]


In [18]:
# Test Case 6: Single Observed Row with Scalar Va (Corrected)
print("\nPython Test Case 6: Single Observed Row with Scalar Va")

# Existing parameter matrix A with 1 observed row and 2 components
A = np.array([
    [100.0, 200.0]
])

# Covariance information as a list (cell array in MATLAB)
Av = [
    np.array([[10, 0],
              [0, 10]])
]

# Observed row indices (1-based)
Ir = [2]

# Total number of rows after addition
n1x = 3

# Variance of the prior for A (vector to match ncomp=2)
Va = [7, 7]  # Changed from scalar to list

# Call the function
A_new, Av_new = add_m_rows(A, Av, Ir, n1x, Va)

print("A_new:")
print(A_new)
print("\nAv_new:")
display_av_new(Av_new)



Python Test Case 6: Single Observed Row with Scalar Va
A_new:
[[  0.   0.]
 [100. 200.]
 [  0.   0.]]

Av_new:
Row 1:
[[7 0]
 [0 7]]
Row 2:
[[10  0]
 [ 0 10]]
Row 3:
[[7 0]
 [0 7]]


In [9]:
# Test Case 7: No Components (ncomp = 0

print("\nPython Test Case 7: No Components (ncomp = 0)")

# Existing parameter matrix A with 2 observed rows and 0 components
A = np.array([]).reshape(2, 0)  # Shape: (2,0), ncomp=0

# Covariance information as an empty list
Av = []

# Observed row indices (1-based)
Ir = [1, 2]

# Total number of rows after addition
n1x = 2

# Variance of the prior for A (empty, since ncomp=0)
Va = []

# Call the function
A_new, Av_new = add_m_rows(A, Av, Ir, n1x, Va)

print("A_new:")
print(A_new)
print("\nAv_new:")
print(Av_new)  # Should be empty



Python Test Case 7: No Components (ncomp = 0)
in add m rows
A_new:
[]

Av_new:
[]


In [20]:
# Test Case 8: All Rows Unobserved with Finite Va (Corrected)
print("\nPython Test Case 8: All Rows Unobserved with Finite Va")

# Existing parameter matrix A is empty (no observed rows) with 2 components
A = np.array([]).reshape(0, 2)  # Shape: (0,2), ncomp=2

# Covariance information is empty
Av = []

# Observed row indices are empty
Ir = []

# Total number of rows after addition
n1x = 3

# Variance of the prior for A (finite)
Va = [4, 4]  # Changed from empty to list matching ncomp=2

# Call the function
A_new, Av_new = add_m_rows(A, Av, Ir, n1x, Va)

print("A_new:")
print(A_new)
print("\nAv_new:")
display_av_new(Av_new)



Python Test Case 8: All Rows Unobserved with Finite Va
A_new:
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Av_new:


In [10]:
# Test Case 9: No Rows to Add (n1x = Number of Observed Rows

print("\nPython Test Case 9: No Rows to Add (n1x = Number of Observed Rows)")

# Existing parameter matrix A with 2 observed rows and 3 components
A = np.array([
    [5.0, 10.0, 15.0],
    [20.0, 25.0, 30.0]
])

# Covariance information as a list (cell array in MATLAB)
Av = [
    np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]]),
    np.array([[2, 0, 0],
              [0, 2, 0],
              [0, 0, 2]])
]

# Observed row indices (all rows since n1x = number of observed rows)
Ir = [1, 2]

# Total number of rows after addition (same as observed)
n1x = 2

# Variance of the prior for A
Va = [6, 6, 6]  # Length matches ncomp=3

# Call the function
A_new, Av_new = add_m_rows(A, Av, Ir, n1x, Va)

print("A_new:")
print(A_new)
print("\nAv_new:")
display_av_new(Av_new)



Python Test Case 9: No Rows to Add (n1x = Number of Observed Rows)
in add m rows
A_new:
[[ 5. 10. 15.]
 [20. 25. 30.]]

Av_new:
Row 1:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Row 2:
[[2 0 0]
 [0 2 0]
 [0 0 2]]


In [11]:
# Test Case 10: Unobserved Rows with Mixed Covariance Information

print("\nPython Test Case 10: Unobserved Rows with Mixed Covariance Information")

# Existing parameter matrix A with 2 observed rows and 2 components
A = np.array([
    [12.0, 24.0],
    [36.0, 48.0]
])

# Covariance information as a list (cell array in MATLAB)
Av = [
    np.array([[1.2, 0],
              [0, 1.2]]),
    np.array([[2.4, 0],
              [0, 2.4]])
]

# Observed row indices (1-based)
Ir = [1, 4]

# Total number of rows after addition
n1x = 5

# Variance of the prior for A (mixed)
Va = [3, np.inf]  # First component finite, second component infinite

# Call the function
A_new, Av_new = add_m_rows(A, Av, Ir, n1x, Va)

print("A_new:")
print(A_new)
print("\nAv_new:")
display_av_new(Av_new)



Python Test Case 10: Unobserved Rows with Mixed Covariance Information
in add m rows
A_new:
[[12. 24.]
 [nan nan]
 [nan nan]
 [36. 48.]
 [nan nan]]

Av_new:
Row 1:
[[1.2 0. ]
 [0.  1.2]]
Row 2:
[[ 3.  0.]
 [ 0. inf]]
Row 3:
[[ 3.  0.]
 [ 0. inf]]
Row 4:
[[2.4 0. ]
 [0.  2.4]]
Row 5:
[[ 3.  0.]
 [ 0. inf]]
